#!/bin/bash
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
wget -O /etc/yum.repos.d/k8.repo https://raw.githubusercontent.com/gangireddydanam/automation1/master/k8/k8.repo
sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/redhat-rhui.repo
yum install -y docker kubelet kubeadm kubectl kubernetes-cni --nogpgcheck
systemctl enable docker && systemctl start docker
systemctl enable kubelet && systemctl start kubelet
sysctl -w net.bridge.bridge-nf-call-iptables=1
echo "net.bridge.bridge-nf-call-iptables=1" > /etc/sysctl.d/k8s.conf
